<div class="login-page">
    <div class="login-container d-flex justify-content-center align-items-center vh-100">
        <div class="login-box shadow p-4 rounded">
            <h2 class="text-center mb-4">Cadastro</h2>

            <form action="/login/salvarCadastro" method="post" class="d-flex flex-column gap-3">
                <div class="form-group">
                    <label for="nome">Nome completo</label>
                    <input type="text" name="nome" id="nome" class="form-control" required>
                </div>

                <div class="form-group">
                    <label for="email">E-mail</label>
                    <input type="email" name="email" id="email" class="form-control" required>
                </div>

                <div class="form-group">
                    <label for="senha">Senha</label>
                    <input type="password" name="senha" id="senha" class="form-control" required>
                </div>

                <div class="form-group">
                    <label for="confirmar_senha">Confirmar Senha</label>
                    <input type="password" name="confirmar_senha" id="confirmar_senha" class="form-control" required>
                </div>

                <button type="submit" class="btn btn-primary fw-bold">Cadastrar</button>
            </form>

            <div class="text-center mt-3">
                <small>Já tem conta? <a href="?page=login" class="fw-bold">Entrar</a></small>
            </div>
        </div>
    </div>
</div>
