<?php require_once 'partials/header.phtml'; ?>
<div class="criar-planilha-page">
    <div class="form-card">
        <h2>Criar Nova Planilha</h2>
        <form action="index.php?page=salvarPlanilha" method="post" class="d-flex flex-column gap-3">
            <div class="form-group">
                <label for="nm_planilha">Nome da Planilha</label>
                <input type="text" name="nm_planilha" id="nm_planilha" class="form-control" required>
            </div>
            <div class="form-group mt-3">
                <label for="descricao">Descrição (Opcional)</label>
                <textarea name="descricao" id="descricao" class="form-control"></textarea>
            </div>
            <button type="submit" class="btn btn-primary mt-4">Salvar Planilha</button>
        </form>
    </div>
</div>
<?php require_once 'partials/footer.phtml'; ?>