<div class="bannerIndex mx-auto">
        <h2>Organize seus treinos, evolua seus resultados</h2>
        <div>
            <a href="index.php?page=criarPlanilha" class="btn btn-lg btn-primary">Comece agora</a>
            
            <a href="index.php?page=planilhas" class="btn btn-lg btn-primary">Ver planilhas</a>
        </div>
    </div>

   <div class="planilhaHome">
    <h2>As melhores planilhas</h2>
    <section class="carrossel">
        <?php if (!empty($planilhasProntas)): ?>
            <?php foreach ($planilhasProntas as $plano): ?>
                <div class="carrossel-card">
                    <h3><?php echo htmlspecialchars($plano->getNmPlanilha()); ?></h3>
                    <p class="description-text"><?php echo htmlspecialchars($plano->getDescricao()); ?></p>
                    <a href="index.php?page=usarPlanilha&id=<?php echo $plano->getId(); ?>" class="btn btn-lg btn-primary">
                        Usar Agora
                    </a>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <p class="no-templates-text">Nenhuma planilha pronta encontrada. Tente adicioná-las no banco de dados.</p>
        <?php endif; ?>
    </section>
</div>

<section class="beneficios">
  <h2>Por que usar o GymNotes?</h2>
  <div class="beneficios-container">
    <div class="beneficio">
      <div class="icon"></div>
      <p>Controle suas cargas</p>
    </div>
    <div class="beneficio">
      <div class="icon"></div>
      <p>Planilhas prontas</p>
    </div>
    <div class="beneficio">
      <div class="icon"></div>
      <p>Biblioteca de exercícios</p>
    </div>
  </div>
</section>

