<div class="bannerIndex mx-auto ">
    <h2>Organize seus treinos, evolua seus resultados</h2>
    <div>
        <a href="" class="btn btn-lg btn-primary">Comece agora</a>
        <a href="" class="btn btn-lg btn-primary">Ver planilhas</a>
    </div>
</div>
<div class="planilhaHome">
    <h2 class="tituloPlanilhas">As melhores planilhas</h2>
    <section class="carrossel">
        <div class="carrossel-card">
            <h3>Full Body</h3>
            <a href="" class="btn btn-lg btn-primary">Usar Agora</a>
        </div>
        <div class="carrossel-card">
            <h3>Upper/Lower</h3>
            <a href="" class="btn btn-lg btn-primary">Usar Agora</a>
        </div>
        <div class="carrossel-card">
            <h3>Push/Pull/Legs</h3>
            <a href="" class="btn btn-lg btn-primary">Usar Agora</a>
        </div>
    </section>

</div>